FROM python:3.8

WORKDIR /src
COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt


EXPOSE 8100

CMD ["uvicorn", "main.app", "--reload", "--host", "0.0.0.0", "--port", "8100"]
