[tool.poetry]
name = "menta-login-backend"
version = "0.0.1"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
uvicorn = {extras = ["standard"], version = ">=0.32.1,<0.33.0"}
pydantic = {extras = ["email"], version = ">=2.0.0,<2.1.0"}
requests = ">=2.32.3,<2.33.0"
fastapi = ">=0.124.4,<0.125.0"
python-multipart = ">=0.0.12,<0.0.13"
pyjwt = ">=1.7.1,<1.8.0"
motor = ">=3.6.0,<3.7.0"
pymongo = ">=4.9.0,<4.10.0"
boto3 = ">=1.35.47,<1.36.0"
Pillow = ">=11.0.0,<11.1.0"
cryptography = ">=43.0.1,<44.0.0"
botocore = ">=1.35.47,<1.36.0"
mangum = ">=0.17.0,<0.18.0"
bcrypt = ">=4.0.1,<5"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

